import assert from "node:assert/strict";
import { webcrypto } from "node:crypto";
Object.defineProperty(globalThis, "crypto", { value: webcrypto });
import { EditorHistory } from "../src/model/editorHistory";
import { exampleScene, equalScene } from "../src/model/sceneEditor";
import { copySelection, pasteSelection, removeSelection, selectedObjectIds } from "../src/model/sceneClipboard";
import { cabinetClearanceViolations } from "../src/model/cabinetPlacement";
import { buildSourceInstance } from "../src/model/field";

const s = exampleScene();
s.microphones = [{id:"microphone-1", name:"Probe",positionX:2,positionHeightM:1.2,positionZ:6}];
s.selectedInstances = [s.sourceConfigs[0].id, s.sourceConfigs[1].id,"microphone-1", "audience-plane"];
const h = new EditorHistory(s,equalScene);
const clip = copySelection(s,h.session);
const pasted = pasteSelection(s,clip,h.session);
assert.equal(pasted.sourceConfigs.length,4); assert.equal(pasted.microphones.length,2);
assert.equal(pasted.selectedInstances.length,4);
const offset = pasted.sourceConfigs[2].positionX-s.sourceConfigs[0].positionX;
assert.ok(Math.abs(pasted.sourceConfigs[3].positionX-s.sourceConfigs[1].positionX-offset)<1e-10);
assert.ok(Math.abs(pasted.microphones[1].positionX-s.microphones[0].positionX-offset)<1e-10);
assert.equal(pasted.sourceConfigs[2].channelId,s.sourceConfigs[0].channelId);
assert.equal(cabinetClearanceViolations(new Map(s.packages.map(p=>[p.id,p])),pasted.sourceConfigs.map(buildSourceInstance)).length,0);
const twice = pasteSelection(pasted,clip,h.session);
assert.equal(new Set(twice.sourceConfigs.map(o=>o.id)).size,6);
assert.equal(cabinetClearanceViolations(new Map(s.packages.map(p=>[p.id,p])),twice.sourceConfigs.map(buildSourceInstance)).length,0);
h.run("Paste 3 objects",()=>h.update(pasted)); h.undo(); assert.equal(h.present,s); h.redo(); assert.equal(h.present,pasted);
assert.equal(h.present.packages[0],s.packages[0],"Assets are shared, not copied per history step");
h.begin("Move group");
for(let i=0;i<20;i++) h.set("sourceConfigs", old=>old.map(o=>({...o,positionZ:o.positionZ+1})));
h.end(); h.undo(); assert.equal(h.present,pasted,"One drag is one undo step");
h.undo(); assert.equal(h.present,s); h.redo();
h.run("Cut",()=>h.update(removeSelection(h.present,selectedObjectIds(h.present))));
const cut=h.present; h.undo(); assert.equal(h.present,pasted); h.redo(); assert.equal(h.present,cut);
h.undo(); h.run("New edit",()=>h.set("projectName","Changed")); assert.equal(h.getSnapshot().redoLabel,null);
h.run("No-op",()=>h.set("sourceConfigs",old=>old.map(o=>({...o})))); assert.equal(h.getSnapshot().undoLabel,"New edit");
const session=h.session; h.clear(); assert.equal(h.getSnapshot().undoLabel,null); assert.notEqual(h.session,session);
assert.throws(()=>pasteSelection(s,clip,h.session),/current open project/);
assert.throws(()=>pasteSelection(s,'not json',session),/Clipboard/);
assert.equal(pasted.audiencePlanes.length,2);
assert.equal(pasted.audiencePlanes[1].centerXM-s.audiencePlanes[0].centerXM,offset);
const corrupt=JSON.parse(clip); corrupt.sources[0].positionX="bad";
assert.throws(()=>pasteSelection(s,JSON.stringify(corrupt),session));
const missing=JSON.parse(clip); missing.sources[0].packageId="absent";
assert.throws(()=>pasteSelection(s,JSON.stringify(missing),session),/package/);
const cutPaste=pasteSelection(removeSelection(s,selectedObjectIds(s)),clip,session);
assert.ok(cutPaste.selectedInstances.every(id=>!s.selectedInstances.includes(id)),"Cut/paste allocates new IDs");
const bounded=new EditorHistory(0,(a,b)=>a===b,3);
for(let n=1;n<=5;n++) bounded.run("step",()=>bounded.update(n));
for(let n=0;n<10;n++) bounded.undo(); assert.equal(bounded.present,2,"History stays bounded");
console.log("Scene clipboard and transactional history passed");
